import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair, Roboto } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar"


const playfair =  Playfair({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: '--font-playfair'
})

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100","200","300", "400", "500", "600", "700", "800", "900"],
  variable: '--font-roboto'
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfair.variable} ${roboto.variable} antialiased`}
      >
        <Navbar/>
        {children}
        <Footer/>
        
      </body>
    </html>
  );
}
